# Generated by Django 5.2.4 on 2025-10-05 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshop', '0002_product_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='size',
            field=models.PositiveIntegerField(default=20),
        ),
    ]
